FROM python:3.9
WORKDIR /app
COPY ./requirements-controller.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt
COPY ./controller.py .
EXPOSE 8000
CMD ["uvicorn", "controller:app", "--host", "0.0.0.0", "--port", "8000"]